# Get editor completions based on the config schema
# add_newline = true
"$schema" = 'https://starship.rs/config-schema.json'

[aws]
disabled = true

[directory]
truncation_length = 1

[git_branch]
truncation_length = 13
truncation_symbol = ""

[character]
success_symbol = "[ğŸ»](bold green)"
